### ISSUE TITLE
Link to the documentation

### ISSUE THREAD

**Issue by Jako** [sergant210/dbAdmin#6]
Hello Sergey, can you add a GitHub Page in https://github.com/sergant210/dbAdmin/settings/pages that uses the gh-pages branch as the documentation?

It will look like this: https://jako.github.io/dbAdmin/ but on this url: https://sergant210.github.io/dbAdmin/

**Comment by sergant210** [comment]
Ok. I need time to sort this out.

**Comment by Jako** [comment]
On my fork the settings are made like this:

![Screenshot](https://user-images.githubusercontent.com/148371/233070142-83d385be-4f40-4241-b45f-70fe22e7ca22.png)

**Comment by sergant210** [comment]
Done. Thanks!
